--This file is generated by tools/genGameAPI, do not modify it manually.
---@meta

---@class py.GameAPI
GameAPI = {}

--Gets the unit number SITE_STATE key-value pair
---@param unit_key py.UnitKey # Unit number
---@param key string # Key name
---@return py.SITE_STATE # Key value
function GameAPI.get_unit_key_site_state_kv(unit_key, key) end

--Gets item number SITE_STATE key-value pair
---@param item_key py.ItemKey # Item number
---@param key string # Key name
---@return py.SITE_STATE # Key value
function GameAPI.get_item_key_site_state_kv(item_key, key) end

--Obtain the skill number SITE_STATE key and value pair
---@param ability_key py.AbilityKey # Skill number
---@param key string # Key name
---@return py.SITE_STATE # Key value
function GameAPI.get_ability_key_site_state_kv(ability_key, key) end

--Get Magic effect number SITE_STATE key pair
---@param modifier_key py.ModifierKey # Magic effect number
---@param key string # Key name
---@return py.SITE_STATE # Key value
function GameAPI.get_modifier_key_site_state_kv(modifier_key, key) end

--Gets the special effect number SITE_STATE key-value pair
---@param projectile_key py.ProjectileKey # Special effect number
---@param key string # Key name
---@return py.SITE_STATE # Key value
function GameAPI.get_projectile_key_site_state_kv(projectile_key, key) end

--Gets the destructible number SITE_STATE key-value pair
---@param destructible_key py.DestructibleKey # Destructible number
---@param key string # Key name
---@return py.SITE_STATE # Key value
function GameAPI.get_destructible_key_site_state_kv(destructible_key, key) end

--Gets the technology number SITE_STATE key-value pair
---@param tech_key py.TechKey # Technology number
---@param key string # Key name
---@return py.SITE_STATE # Key value
function GameAPI.get_tech_key_site_state_kv(tech_key, key) end

--Gets the image SITE_STATE key-value pair
---@param icon_id py.Texture # picture
---@param key string # Key name
---@return py.SITE_STATE # Key value
function GameAPI.get_icon_id_site_state_kv(icon_id, key) end

--Obtain the SITE_STATE key-value pair of the logical physical component type
---@param physics_entity_key py.PhysicsEntityKey # Logical physical component type
---@param key string # Key name
---@return py.SITE_STATE # Key value
function GameAPI.get_physics_entity_key_site_state_kv(physics_entity_key, key) end

--Gets the SITE_STATE key-value pair
---@param kvbase py.KVBase # Custom key value carrier
---@param key string # Key name
---@return py.SITE_STATE # Key value
function GameAPI.get_kv_pair_value_site_state(kvbase, key) end

--Gets the unit number COIN_CURRENCY key-value pair
---@param unit_key py.UnitKey # Unit number
---@param key string # Key name
---@return py.COIN_CURRENCY # Key value
function GameAPI.get_unit_key_coin_currency_kv(unit_key, key) end

--Gets the item number COIN_CURRENCY key value pair
---@param item_key py.ItemKey # Item number
---@param key string # Key name
---@return py.COIN_CURRENCY # Key value
function GameAPI.get_item_key_coin_currency_kv(item_key, key) end

--Gets the skill number COIN_CURRENCY key value pair
---@param ability_key py.AbilityKey # Skill number
---@param key string # Key name
---@return py.COIN_CURRENCY # Key value
function GameAPI.get_ability_key_coin_currency_kv(ability_key, key) end

--Get the Magic effect number COIN_CURRENCY key pair
---@param modifier_key py.ModifierKey # Magic effect number
---@param key string # Key name
---@return py.COIN_CURRENCY # Key value
function GameAPI.get_modifier_key_coin_currency_kv(modifier_key, key) end

--Gets the special effect number COIN_CURRENCY key-value pair
---@param projectile_key py.ProjectileKey # Special effect number
---@param key string # Key name
---@return py.COIN_CURRENCY # Key value
function GameAPI.get_projectile_key_coin_currency_kv(projectile_key, key) end

--Gets the destructible number COIN_CURRENCY key-value pair
---@param destructible_key py.DestructibleKey # Destructible number
---@param key string # Key name
---@return py.COIN_CURRENCY # Key value
function GameAPI.get_destructible_key_coin_currency_kv(destructible_key, key) end

--Get the technology number COIN_CURRENCY key value pair
---@param tech_key py.TechKey # Technology number
---@param key string # Key name
---@return py.COIN_CURRENCY # Key value
function GameAPI.get_tech_key_coin_currency_kv(tech_key, key) end

--Get the picture COIN_CURRENCY key pair
---@param icon_id py.Texture # picture
---@param key string # Key name
---@return py.COIN_CURRENCY # Key value
function GameAPI.get_icon_id_coin_currency_kv(icon_id, key) end

--Gets a logical physical component type COIN_CURRENCY key-value pair
---@param physics_entity_key py.PhysicsEntityKey # Logical physical component type
---@param key string # Key name
---@return py.COIN_CURRENCY # Key value
function GameAPI.get_physics_entity_key_coin_currency_kv(physics_entity_key, key) end

--Gets the COIN_CURRENCY key-value pair
---@param kvbase py.KVBase # Custom key value carrier
---@param key string # Key name
---@return py.COIN_CURRENCY # Key value
function GameAPI.get_kv_pair_value_coin_currency(kvbase, key) end

--Gets the global trigger UI_CHAT_SEND_CHANNEL non-array variable
---@param key string # Variable name
---@return integer # value
function GameAPI.get_trigger_variable_ui_chat_send_channel(key) end

--Gets the trigger UI_CHAT_SEND_CHANNEL non-array group variable
---@param actor py.Actor # Unit entity
---@param key string # Variable name
---@return integer # value
function GameAPI.get_trigger_actor_variable_ui_chat_send_channel(actor, key) end

--Gets the global trigger UI_CHAT_SEND_CHANNEL array variable subentry
---@param key string # Variable name
---@param index integer # subscript
---@return integer # value
function GameAPI.get_trigger_list_variable_ui_chat_send_channel(key, index) end

--Gets the trigger UI_CHAT_SEND_CHANNEL array group variable subentry
---@param actor py.Actor # Unit entity
---@param key string # Variable name
---@param index integer # subscript
---@return integer # value
function GameAPI.get_trigger_list_actor_variable_ui_chat_send_channel(actor, key, index) end

--Gets the global trigger UI_CHAT_SEND_CHANNEL array variable
---@param key string # Variable name
---@return py.List # Array type variable value
function GameAPI.get_trigger_list_variable_all_ui_chat_send_channel(key) end

--Gets the trigger UI_CHAT_SEND_CHANNEL group variable array
---@param actor py.Actor # Unit entity
---@param key string # Variable name
---@return py.List # Array type variable value
function GameAPI.get_trigger_list_actor_variable_all_ui_chat_send_channel(actor, key) end

--Gets the global trigger UI_CHAT_RECV_CHANNEL non-array variable
---@param key string # Variable name
---@return integer # value
function GameAPI.get_trigger_variable_ui_chat_recv_channel(key) end

--Gets the trigger UI_CHAT_RECV_CHANNEL non-array group variable
---@param actor py.Actor # Unit entity
---@param key string # Variable name
---@return integer # value
function GameAPI.get_trigger_actor_variable_ui_chat_recv_channel(actor, key) end

--Gets the global trigger UI_CHAT_RECV_CHANNEL array variable subentry
---@param key string # Variable name
---@param index integer # subscript
---@return integer # value
function GameAPI.get_trigger_list_variable_ui_chat_recv_channel(key, index) end

--Gets the trigger UI_CHAT_RECV_CHANNEL array group variable subentry
---@param actor py.Actor # Unit entity
---@param key string # Variable name
---@param index integer # subscript
---@return integer # value
function GameAPI.get_trigger_list_actor_variable_ui_chat_recv_channel(actor, key, index) end

--Gets the global trigger UI_CHAT_RECV_CHANNEL array variable
---@param key string # Variable name
---@return py.List # Array type variable value
function GameAPI.get_trigger_list_variable_all_ui_chat_recv_channel(key) end

--Gets the trigger UI_CHAT_RECV_CHANNEL group variable array
---@param actor py.Actor # Unit entity
---@param key string # Variable name
---@return py.List # Array type variable value
function GameAPI.get_trigger_list_actor_variable_all_ui_chat_recv_channel(actor, key) end

--Gets the global trigger GOODS_KEY non-array variable
---@param key string # Variable name
---@return py.GoodsKey # value
function GameAPI.get_trigger_variable_goods_key(key) end

--Gets the trigger GOODS_KEY non-array group variable
---@param actor py.Actor # Unit entity
---@param key string # Variable name
---@return py.GoodsKey # value
function GameAPI.get_trigger_actor_variable_goods_key(actor, key) end

--Gets the global trigger GOODS_KEY array variable subentry
---@param key string # Variable name
---@param index integer # subscript
---@return py.GoodsKey # value
function GameAPI.get_trigger_list_variable_goods_key(key, index) end

--Gets the trigger GOODS_KEY array group variable subentry
---@param actor py.Actor # Unit entity
---@param key string # Variable name
---@param index integer # subscript
---@return py.GoodsKey # value
function GameAPI.get_trigger_list_actor_variable_goods_key(actor, key, index) end

--Gets the global trigger GOODS_KEY array variable
---@param key string # Variable name
---@return py.List # Array type variable value
function GameAPI.get_trigger_list_variable_all_goods_key(key) end

--Gets an array of trigger GOODS_KEY group variables
---@param actor py.Actor # Unit entity
---@param key string # Variable name
---@return py.List # Array type variable value
function GameAPI.get_trigger_list_actor_variable_all_goods_key(actor, key) end

--Gets the global trigger SITE_STATE non-array variable
---@param key string # Variable name
---@return py.SITE_STATE # value
function GameAPI.get_trigger_variable_site_state(key) end

--Gets trigger SITE_STATE non-array group variable
---@param actor py.Actor # Unit entity
---@param key string # Variable name
---@return py.SITE_STATE # value
function GameAPI.get_trigger_actor_variable_site_state(actor, key) end

--Gets the global trigger SITE_STATE array variable subentry
---@param key string # Variable name
---@param index integer # subscript
---@return py.SITE_STATE # value
function GameAPI.get_trigger_list_variable_site_state(key, index) end

--Gets the trigger SITE_STATE array group variable subentry
---@param actor py.Actor # Unit entity
---@param key string # Variable name
---@param index integer # subscript
---@return py.SITE_STATE # value
function GameAPI.get_trigger_list_actor_variable_site_state(actor, key, index) end

--Gets the global trigger SITE_STATE array variable
---@param key string # Variable name
---@return py.List # Array type variable value
function GameAPI.get_trigger_list_variable_all_site_state(key) end

--Gets an array of trigger SITE_STATE group variables
---@param actor py.Actor # Unit entity
---@param key string # Variable name
---@return py.List # Array type variable value
function GameAPI.get_trigger_list_actor_variable_all_site_state(actor, key) end

--Gets the global trigger COIN_CURRENCY non-array variable
---@param key string # Variable name
---@return py.COIN_CURRENCY # value
function GameAPI.get_trigger_variable_coin_currency(key) end

--Gets the trigger COIN_CURRENCY non-array group variable
---@param actor py.Actor # Unit entity
---@param key string # Variable name
---@return py.COIN_CURRENCY # value
function GameAPI.get_trigger_actor_variable_coin_currency(actor, key) end

--Gets the global trigger COIN_CURRENCY array variable subentry
---@param key string # Variable name
---@param index integer # subscript
---@return py.COIN_CURRENCY # value
function GameAPI.get_trigger_list_variable_coin_currency(key, index) end

--Gets the trigger COIN_CURRENCY array group variable subentry
---@param actor py.Actor # Unit entity
---@param key string # Variable name
---@param index integer # subscript
---@return py.COIN_CURRENCY # value
function GameAPI.get_trigger_list_actor_variable_coin_currency(actor, key, index) end

--Gets the global trigger COIN_CURRENCY array variable
---@param key string # Variable name
---@return py.List # Array type variable value
function GameAPI.get_trigger_list_variable_all_coin_currency(key) end

--Gets an array of trigger COIN_CURRENCY group variables
---@param actor py.Actor # Unit entity
---@param key string # Variable name
---@return py.List # Array type variable value
function GameAPI.get_trigger_list_actor_variable_all_coin_currency(actor, key) end

--Sets the global trigger UI_CHAT_SEND_CHANNEL array variable subentry
---@param key string # Variable name
---@param index integer # subscript
---@param value? integer # value
function GameAPI.set_trigger_list_variable_ui_chat_send_channel(key, index, value) end

--Sets the global trigger UI_CHAT_SEND_CHANNEL array group variable subentry
---@param actor py.Actor # Unit entity
---@param key string # Variable name
---@param index integer # subscript
---@param value? integer # value
function GameAPI.set_trigger_list_actor_variable_ui_chat_send_channel(actor, key, index, value) end

--Sets the global trigger UI_CHAT_SEND_CHANNEL non-array variable
---@param key string # Variable name
---@param value? integer # value
function GameAPI.set_trigger_variable_ui_chat_send_channel(key, value) end

--Sets the global trigger UI_CHAT_SEND_CHANNEL non-array group variable
---@param actor py.Actor # Unit entity
---@param key string # Variable name
---@param value? integer # value
function GameAPI.set_trigger_actor_variable_ui_chat_send_channel(actor, key, value) end

--Sets the global trigger UI_CHAT_RECV_CHANNEL array variable subentry
---@param key string # Variable name
---@param index integer # subscript
---@param value? integer # value
function GameAPI.set_trigger_list_variable_ui_chat_recv_channel(key, index, value) end

--Sets the global trigger UI_CHAT_RECV_CHANNEL array group variable subentry
---@param actor py.Actor # Unit entity
---@param key string # Variable name
---@param index integer # subscript
---@param value? integer # value
function GameAPI.set_trigger_list_actor_variable_ui_chat_recv_channel(actor, key, index, value) end

--Sets the global trigger UI_CHAT_RECV_CHANNEL non-array variable
---@param key string # Variable name
---@param value? integer # value
function GameAPI.set_trigger_variable_ui_chat_recv_channel(key, value) end

--Sets the global trigger UI_CHAT_RECV_CHANNEL non-array group variable
---@param actor py.Actor # Unit entity
---@param key string # Variable name
---@param value? integer # value
function GameAPI.set_trigger_actor_variable_ui_chat_recv_channel(actor, key, value) end

--Sets the global trigger GOODS_KEY array variable subentry
---@param key string # Variable name
---@param index integer # subscript
---@param value? py.GoodsKey # value
function GameAPI.set_trigger_list_variable_goods_key(key, index, value) end

--Sets the global trigger GOODS_KEY array group variable subentry
---@param actor py.Actor # Unit entity
---@param key string # Variable name
---@param index integer # subscript
---@param value? py.GoodsKey # value
function GameAPI.set_trigger_list_actor_variable_goods_key(actor, key, index, value) end

--Sets the global trigger GOODS_KEY non-array variable
---@param key string # Variable name
---@param value? py.GoodsKey # value
function GameAPI.set_trigger_variable_goods_key(key, value) end

--Sets the global trigger GOODS_KEY non-array group variable
---@param actor py.Actor # Unit entity
---@param key string # Variable name
---@param value? py.GoodsKey # value
function GameAPI.set_trigger_actor_variable_goods_key(actor, key, value) end

--Sets the global trigger SITE_STATE array variable subentry
---@param key string # Variable name
---@param index integer # subscript
---@param value? py.SITE_STATE # value
function GameAPI.set_trigger_list_variable_site_state(key, index, value) end

--Sets the global trigger SITE_STATE array group variable subentry
---@param actor py.Actor # Unit entity
---@param key string # Variable name
---@param index integer # subscript
---@param value? py.SITE_STATE # value
function GameAPI.set_trigger_list_actor_variable_site_state(actor, key, index, value) end

--Sets the global trigger SITE_STATE non-array variable
---@param key string # Variable name
---@param value? py.SITE_STATE # value
function GameAPI.set_trigger_variable_site_state(key, value) end

--Sets the global trigger SITE_STATE non-array group variable
---@param actor py.Actor # Unit entity
---@param key string # Variable name
---@param value? py.SITE_STATE # value
function GameAPI.set_trigger_actor_variable_site_state(actor, key, value) end

--Sets the global trigger COIN_CURRENCY array variable subentry
---@param key string # Variable name
---@param index integer # subscript
---@param value? py.COIN_CURRENCY # value
function GameAPI.set_trigger_list_variable_coin_currency(key, index, value) end

--Sets the global trigger COIN_CURRENCY array group variable subentry
---@param actor py.Actor # Unit entity
---@param key string # Variable name
---@param index integer # subscript
---@param value? py.COIN_CURRENCY # value
function GameAPI.set_trigger_list_actor_variable_coin_currency(actor, key, index, value) end

--Sets the global trigger COIN_CURRENCY non-array variable
---@param key string # Variable name
---@param value? py.COIN_CURRENCY # value
function GameAPI.set_trigger_variable_coin_currency(key, value) end

--Sets the global trigger COIN_CURRENCY non-array group variable
---@param actor py.Actor # Unit entity
---@param key string # Variable name
---@param value? py.COIN_CURRENCY # value
function GameAPI.set_trigger_actor_variable_coin_currency(actor, key, value) end

--Gets an item in the SITE_STATE array
---@param l py.List # list
---@param i integer # subscript
---@return py.SITE_STATE # value
function GameAPI.get_site_state_list_value(l, i) end

--Sets an item in the SITE_STATE array
---@param l py.List # list
---@param i integer # subscript
---@param v py.SITE_STATE # value
function GameAPI.set_site_state_list_value(l, i, v) end

--Generates an array of n SITE_STATE values of v
---@param n integer # Length
---@param v? py.SITE_STATE # value
---@return py.List # list
function GameAPI.get_site_state_n_list(n, v) end

--Gets an item in the COIN_CURRENCY array
---@param l py.List # list
---@param i integer # subscript
---@return py.COIN_CURRENCY # value
function GameAPI.get_coin_currency_list_value(l, i) end

--Sets an item in the COIN_CURRENCY array
---@param l py.List # list
---@param i integer # subscript
---@param v py.COIN_CURRENCY # value
function GameAPI.set_coin_currency_list_value(l, i, v) end

--Generates an array of n COIN_CURRENCY values of v
---@param n integer # Length
---@param v? py.COIN_CURRENCY # value
---@return py.List # list
function GameAPI.get_coin_currency_n_list(n, v) end

--Gets an item in the GOODS_KEY array
---@param l py.List # list
---@param i integer # subscript
---@return py.GoodsKey # value
function GameAPI.get_goods_key_list_value(l, i) end

--Sets an item in the GOODS_KEY array
---@param l py.List # list
---@param i integer # subscript
---@param v py.GoodsKey # value
function GameAPI.set_goods_key_list_value(l, i, v) end

--Generates n GOODS_KEY arrays of value v
---@param n integer # Length
---@param v? py.GoodsKey # value
---@return py.List # list
function GameAPI.get_goods_key_n_list(n, v) end

--Gets an item in the UI_CHAT_SEND_CHANNEL array
---@param l py.List # list
---@param i integer # subscript
---@return integer # value
function GameAPI.get_ui_chat_send_channel_list_value(l, i) end

--Sets an item in the UI_CHAT_SEND_CHANNEL array
---@param l py.List # list
---@param i integer # subscript
---@param v integer # value
function GameAPI.set_ui_chat_send_channel_list_value(l, i, v) end

--Generates n UI_CHAT_SEND_CHANNEL arrays with value v
---@param n integer # Length
---@param v? integer # value
---@return py.List # list
function GameAPI.get_ui_chat_send_channel_n_list(n, v) end

--Gets an item in the UI_CHAT_RECV_CHANNEL array
---@param l py.List # list
---@param i integer # subscript
---@return integer # value
function GameAPI.get_ui_chat_recv_channel_list_value(l, i) end

--Sets an item in the UI_CHAT_RECV_CHANNEL array
---@param l py.List # list
---@param i integer # subscript
---@param v integer # value
function GameAPI.set_ui_chat_recv_channel_list_value(l, i, v) end

--Generates n UI_CHAT_RECV_CHANNEL arrays of value v
---@param n integer # Length
---@param v? integer # value
---@return py.List # list
function GameAPI.get_ui_chat_recv_channel_n_list(n, v) end

--The default library adds UI_CHAT_SEND_CHANNEL key-value pairs
---@param item_key integer # prefab Library ID
---@param key integer # ID
---@param value string # Key-value name
function GameAPI.set_unit_key_ui_chat_send_channel_kv(item_key, key, value) end

--The default library adds UI_CHAT_RECV_CHANNEL key-value pairs
---@param item_key integer # prefab Library ID
---@param key integer # ID
---@param value string # Key-value name
function GameAPI.set_unit_key_ui_chat_recv_channel_kv(item_key, key, value) end

--The default library adds GOODS_KEY key-value pairs
---@param item_key integer # prefab Library ID
---@param key integer # ID
---@param value string # Key-value name
function GameAPI.set_unit_key_goods_key_kv(item_key, key, value) end

--Default libraries add SITE_STATE key-value pairs
---@param item_key integer # prefab Library ID
---@param key integer # ID
---@param value string # Key-value name
function GameAPI.set_unit_key_site_state_kv(item_key, key, value) end

--The default library adds a COIN_CURRENCY key-value pair
---@param item_key integer # prefab Library ID
---@param key integer # ID
---@param value string # Key-value name
function GameAPI.set_unit_key_coin_currency_kv(item_key, key, value) end

--The default library adds UI_CHAT_SEND_CHANNEL key-value pairs
---@param item_key integer # prefab Library ID
---@param key integer # ID
---@param value string # Key-value name
function GameAPI.set_item_key_ui_chat_send_channel_kv(item_key, key, value) end

--The default library adds UI_CHAT_RECV_CHANNEL key-value pairs
---@param item_key integer # prefab Library ID
---@param key integer # ID
---@param value string # Key-value name
function GameAPI.set_item_key_ui_chat_recv_channel_kv(item_key, key, value) end

--The default library adds GOODS_KEY key-value pairs
---@param item_key integer # prefab Library ID
---@param key integer # ID
---@param value string # Key-value name
function GameAPI.set_item_key_goods_key_kv(item_key, key, value) end

--Default libraries add SITE_STATE key-value pairs
---@param item_key integer # prefab Library ID
---@param key integer # ID
---@param value string # Key-value name
function GameAPI.set_item_key_site_state_kv(item_key, key, value) end

--The default library adds a COIN_CURRENCY key-value pair
---@param item_key integer # prefab Library ID
---@param key integer # ID
---@param value string # Key-value name
function GameAPI.set_item_key_coin_currency_kv(item_key, key, value) end

--The default library adds UI_CHAT_SEND_CHANNEL key-value pairs
---@param item_key integer # prefab Library ID
---@param key integer # ID
---@param value string # Key-value name
function GameAPI.set_ability_key_ui_chat_send_channel_kv(item_key, key, value) end

--The default library adds UI_CHAT_RECV_CHANNEL key-value pairs
---@param item_key integer # prefab Library ID
---@param key integer # ID
---@param value string # Key-value name
function GameAPI.set_ability_key_ui_chat_recv_channel_kv(item_key, key, value) end

--The default library adds GOODS_KEY key-value pairs
---@param item_key integer # prefab Library ID
---@param key integer # ID
---@param value string # Key-value name
function GameAPI.set_ability_key_goods_key_kv(item_key, key, value) end

--Default libraries add SITE_STATE key-value pairs
---@param item_key integer # prefab Library ID
---@param key integer # ID
---@param value string # Key-value name
function GameAPI.set_ability_key_site_state_kv(item_key, key, value) end

--The default library adds a COIN_CURRENCY key-value pair
---@param item_key integer # prefab Library ID
---@param key integer # ID
---@param value string # Key-value name
function GameAPI.set_ability_key_coin_currency_kv(item_key, key, value) end

--Gets the number of item groups
---@param item_group py.ItemGroup # Item group
---@return integer # Item group quantity
function GameAPI.api_get_item_group_length(item_group) end

--Sets whether in-game item names are displayed permanently
---@param permanent_show boolean # Display resident or not
function GameAPI.set_item_name_permanent_show_config(permanent_show) end

--Call the screenshot function in Lua
---@param path string # Relative path under LocalData
---@param file_name string # filename
---@param width? integer # Picture width
---@param height? integer # Picture height
function GameAPI.screenshot_func_for_lua(path, file_name, width, height) end

--Reset the center point and radius of the circle area
---@param area py.CirArea # Circular region
---@param center_point py.Point # Central point
---@param radius py.Fixed # radius
function GameAPI.api_reset_cir_area(area, center_point, radius) end

--Reset the start and end of the rectangular area
---@param area py.RecArea # Rectangular region
---@param point_begin py.Point # Initial point
---@param point_end py.Point # End point
function GameAPI.api_reset_rect_two_point(area, point_begin, point_end) end

--Set the ui component picture (picture type)
---@param role py.Role # Player
---@param comp_name string # Control name
---@param image_id py.Texture # picture
function GameAPI.set_ui_comp_image_with_icon_steam(role, comp_name, image_id) end

--Get the player's steam country
---@return py.COIN_CURRENCY # steam currency
function GameAPI.get_steam_player_currency() end

--Get the price of the player's goods in the corresponding country
---@param goods_id string # Product ID
---@return number # Price
function GameAPI.get_steam_goods_price(goods_id) end

--Request the server to purchase an item
---@param role py.Role # Player
---@param count integer # Commodity quantity
---@param no string # Product ID
---@param lua_func function # Callback function
---@param context py.Dict # Callback parameter passing
function GameAPI.lua_request_server_mall_purchase_goods(role, count, no, lua_func, context) end

--steam Create Room
---@param room_name string # Room name
---@param lua_func function # Callback function
---@param context py.Dict # Callback parameter passing
---@param mode_id? integer # Game mode
---@param password? string # Room code
function GameAPI.lua_request_server_create_room(room_name, lua_func, context, mode_id, password) end

--steam requests a list of rooms
---@param lua_func function # Callback function
---@param context py.Dict # Callback parameter passing
---@param page_index string # Room pages
function GameAPI.lua_request_server_room_list_info(lua_func, context, page_index) end

--steam requests to join the room
---@param room_id integer # Room id
---@param lua_func function # Callback function
---@param context py.Dict # Callback parameter passing
---@param password string # Room code
function GameAPI.lua_request_server_join_room(room_id, lua_func, context, password) end

--steam requests room information
---@param aid integer # Player id
---@param lua_func function # Callback function
---@param context py.Dict # Callback parameter passing
function GameAPI.lua_request_server_room_info(aid, lua_func, context) end

--steam requests a room to start the game
---@param lua_func function # Callback function
---@param context py.Dict # Callback parameter passing
function GameAPI.lua_request_server_room_strat_game(lua_func, context) end

--steam invites players to join the room
---@param aid integer # Player id
---@param lua_func function # Callback function
---@param context py.Dict # Callback parameter passing
function GameAPI.lua_request_server_invite_player_join_room(aid, lua_func, context) end

--steam accepts room invitations
---@param aid integer # Player id
---@param room_id integer # Room id
---@param lua_func function # Callback function
---@param context py.Dict # Callback parameter passing
function GameAPI.lua_request_server_reply_room_invite(aid, room_id, lua_func, context) end

--steam exchange room slots
---@param slot_index integer # slot
---@param lua_func function # Callback function
---@param context py.Dict # Callback parameter passing
function GameAPI.lua_request_server_change_room_slot(slot_index, lua_func, context) end

--steam Exchange homeowners
---@param aid integer # Player id
---@param lua_func function # Callback function
---@param context py.Dict # Callback parameter passing
function GameAPI.lua_request_server_change_owner(aid, lua_func, context) end

--steam exit room
---@param aid integer # Player id
---@param lua_func function # Callback function
---@param context py.Dict # Callback parameter passing
function GameAPI.lua_request_server_exit_room(aid, lua_func, context) end

--steam kicked out of the room
---@param aid integer # Player id
---@param lua_func function # Callback function
---@param context py.Dict # Callback parameter passing
function GameAPI.lua_request_server_kick_from_room(aid, lua_func, context) end

--steam changes the location status
---@param slot_index integer # slot
---@param state integer # slot
---@param lua_func function # Callback function
---@param context py.Dict # Callback parameter passing
function GameAPI.lua_request_server_set_site_state(slot_index, state, lua_func, context) end

--steam Change the room password
---@param pass_word string # cipher
---@param lua_func function # Callback function
---@param context py.Dict # Callback parameter passing
function GameAPI.lua_request_server_change_room_password(pass_word, lua_func, context) end

--steam Change the room password
---@param level_min string # Minimum grade
---@param level_max string # Maximum grade
---@param lua_func function # Callback function
---@param context py.Dict # Callback parameter passing
function GameAPI.lua_request_server_change_room_level_limit(level_min, level_max, lua_func, context) end

--The video control starts to play the video
---@param role py.Role # Player
---@param comp_uid string # Control uid
---@param url string # url
---@param ease_in_time? number # Fade duration
---@param ease_out_time? number # Fade duration
---@param ease_type? integer # Curve type
---@param is_loop? boolean # Loop play
function GameAPI.play_ui_video_comp(role, comp_uid, url, ease_in_time, ease_out_time, ease_type, is_loop) end

--Set the rotation of the minimap avatar
---@param role py.Role # Player
---@param comp_name py.Unit # unit
---@param rotation py.Fixed # Rotation
function GameAPI.set_mini_map_icon_rotation(role, comp_name, rotation) end

--Gets the active status of the player joystick
---@param role py.Role # Player
---@param comp_name string # UI control
---@return boolean # Activated or not
function GameAPI.api_get_joystick_move_state(role, comp_name) end

--Get the joystick movement direction
---@param role py.Role # Player
---@param comp_name string # UI control
---@return string # language
function GameAPI.api_get_joystick_move_direction(role, comp_name) end

--Get the force of the stick movement
---@param role py.Role # Player
---@param comp_name string # UI control
---@return string # language
function GameAPI.api_get_joystick_move_percent(role, comp_name) end

--Set the button nine house value in different states
---@param role py.Role # Player
---@param comp_name string # Control uid
---@param btn_status integer # Button state
---@param x_left integer # x
---@param x_right integer # y
---@param y_top integer # width
---@param y_bottom integer # height
function GameAPI.set_ui_btn_status_cap_insets(role, comp_name, btn_status, x_left, x_right, y_top, y_bottom) end

--Set up the UI World chat send channel
---@param player py.Role # Player
---@param comp_name string # UI control
---@param channel integer # channel
function GameAPI.set_ui_world_chat_box_send_channel(player, comp_name, channel) end

--Set the UI World chat receiving channel
---@param player py.Role # Player
---@param comp_name string # UI control
---@param channel integer # channel
function GameAPI.set_ui_world_chat_box_recv_channel(player, comp_name, channel) end

--Block the World Chat send channel
---@param player py.Role # Player
---@param comp_name string # UI control
---@param channel integer # channel
function GameAPI.ban_ui_world_chat_box_send_channel(player, comp_name, channel) end

--Block the World Chat receiving channel
---@param player py.Role # Player
---@param comp_name string # UI control
---@param channel integer # channel
function GameAPI.ban_ui_world_chat_box_recv_channel(player, comp_name, channel) end

--Adds rich text text to the input box
---@param role py.Role # Player
---@param comp_uid string # Control uid
---@param text string # Text
---@param color string # colour
---@param is_bold? boolean # Bold or not
---@param is_underline? boolean # Underline or not
---@param data? string # Callback data
function GameAPI.add_rich_text_text_to_chat_box(role, comp_uid, text, color, is_bold, is_underline, data) end

--Adds a rich text image to the input box
---@param role py.Role # Player
---@param comp_uid string # Control uid
---@param image_id py.Texture # picture
function GameAPI.add_rich_text_pic_to_chat_box(role, comp_uid, image_id) end

--Set the text gradient
---@param role py.Role # Player
---@param comp_uid string # Control name
---@param hex1? string # hex
---@param a1? number # A
---@param hex2? string # hex
---@param a2? number # A
---@param hex3? string # hex
---@param a3? number # A
---@param hex4? string # hex
---@param a4? number # A
---@param enable? boolean # enable
function GameAPI.set_ui_text_gradient_color(role, comp_uid, hex1, a1, hex2, a2, hex3, a3, hex4, a4, enable) end

--[Performance] Whether to ignore the threat priority when retrieving the enemy. Disabled by default. When enabled, the target priority ranking will only consider the distance, no longer consider the threat degree of the target. After opening, the enemy performance will be greatly improved when there are a large number of potential targets in the warning range. If the map gameplay does not have strict requirements for threat priority, it is recommended to open
---@param enable boolean # Enable or not
function GameAPI.set_ai_ignore_threat_priority(enable) end

--Gets the number of times the archive remains
---@param role py.Role # Player
---@param archive_key integer # Integer archive
---@return integer # Archive residuals
function GameAPI.get_role_map_archive_limit(role, archive_key) end

--Create the role top light to the unit mount contact
---@param unit py.Unit # unit
---@param socket_name string # Hanging node
---@param pos_offset_y? py.Fixed # Departure height
---@param target? py.Actor # goal-oriented
---@param target_offset_y? py.Fixed # Offset height towards target
---@param need_shadow? boolean # Whether shadow is generated
---@return py.SpotLight # Directional light source
function GameAPI.create_character_top_light_to_unit_socket(unit, socket_name, pos_offset_y, target, target_offset_y, need_shadow) end

--Disable all ECA global triggers
function GameAPI.disable_all_eca_triggers() end

--Create effects to Magic effects hook model (follow rotation using enumeration)
---@param sfx_id py.SfxKey # Special effect number
---@param unit py.ModifierEntity # Magic effect
---@param editor_model_id py.ModelKey # id of the mount model
---@param socket string # Unit mounting contact
---@param rotate_type integer # Follow rotation mode
---@param b_follow_scale boolean # Whether to scale with units
---@param speed? number # Playback speed
---@param duration? number # duration
---@param angle? number # Angle
---@param immediately? boolean # Whether to delete now
---@param use_sys_d_destroy_way? boolean # Effects delete the way to read table or not
---@param detach? boolean # Whether to leave the unit
---@param show_in_fog? boolean # Show in the mist
---@param blend_with_fog? boolean # Fog mixing
---@param scale_x? number # X-axis scaling
---@param scale_y? number # Y-axis scaling
---@param scale_z? number # Z-axis scaling
---@return py.Sfx # VFX
function GameAPI.create_sfx_on_modifier_attach_model(sfx_id, unit, editor_model_id, socket, rotate_type, b_follow_scale, speed, duration, angle, immediately, use_sys_d_destroy_way, detach, show_in_fog, blend_with_fog, scale_x, scale_y, scale_z) end

--Integer to unit type
---@param int_num integer # integer
---@return py.UnitType # Unit type
function GameAPI.int_transform_unit_type(int_num) end

--Integer transprojectile type
---@param int_num integer # integer
---@return py.ProjectileKey # Projectile type
function GameAPI.int_transform_projectile_type(int_num) end

--Integer transfer item type
---@param int_num integer # integer
---@return py.ItemKey # Item type
function GameAPI.int_transform_item_type(int_num) end

--Integer to magic effect type
---@param int_num integer # integer
---@return py.ModifierType # Magic effect type
function GameAPI.int_transform_modifier_type(int_num) end

--Integer to skill type
---@param int_num integer # integer
---@return py.AbilityKey # Skill type
function GameAPI.int_transform_ability_type(int_num) end

--Integer to technology type
---@param int_num integer # integer
---@return py.TechKey # Science and technology type
function GameAPI.int_transform_tech_type(int_num) end

--Integer to destructible type
---@param int_num integer # integer
---@return py.DestructibleKey # Destructible type
function GameAPI.int_transform_destruct_type(int_num) end

--Integer to sound type
---@param int_num integer # integer
---@return py.AudioKey # Sound type
function GameAPI.int_transform_sound_type(int_num) end

--Request a room name change
---@param room_name string # Room name
---@param lua_func function # Callback function
---@param context py.Dict # Callback parameter passing
function GameAPI.lua_request_change_room_name(room_name, lua_func, context) end

--steam Check your team information
---@param lua_func function # Callback function
---@param context py.Dict # Callback parameter passing
function GameAPI.lua_request_my_team_info(lua_func, context) end

--Create traction direction
---@param target_unit py.Unit # Target unit
---@param force_angle py.Fixed # Directional Angle
---@param speed py.Fixed # speed
---@param max_speed py.Fixed # Maximum speed
---@param min_speed py.Fixed # Minimum speed
---@param acc py.Fixed # acceleration
---@return integer # Tractive object
function GameAPI.create_force_direction(target_unit, force_angle, speed, max_speed, min_speed, acc) end

--Create a traction point
---@param target_unit py.Unit # Target unit
---@param force_point py.Point # Central point
---@param speed py.Fixed # speed
---@param max_speed py.Fixed # Maximum speed
---@param min_speed py.Fixed # Minimum speed
---@param acc py.Fixed # acceleration
---@return integer # Tractive object
function GameAPI.create_force_point(target_unit, force_point, speed, max_speed, min_speed, acc) end

--Create a traction target
---@param target_unit py.Unit # Target unit
---@param force_unit py.Unit # Tractive force unit
---@param speed py.Fixed # speed
---@param max_speed py.Fixed # Maximum speed
---@param min_speed py.Fixed # Minimum speed
---@param acc py.Fixed # acceleration
---@return integer # Tractive object
function GameAPI.create_force_target(target_unit, force_unit, speed, max_speed, min_speed, acc) end

--Copy control text to the clipboard
---@param role py.Role # Player
---@param comp_uid string # Control uid
---@param index1? integer # Initial index
---@param index2? integer # End index
function GameAPI.copy_ui_text_to_clipboard(role, comp_uid, index1, index2) end

--Lens Control - Sets the lens control to bind to the lens
---@param role py.Role # Player
---@param comp_uid string # Control uid
---@param camera_id py.Camera # Lens
function GameAPI.set_ui_camera_binding(role, comp_uid, camera_id) end

--Lens Controls - Set mask map
---@param role py.Role # Player
---@param comp_uid string # Control uid
---@param mask_texture integer # Picture id
function GameAPI.set_ui_camera_mask_texture(role, comp_uid, mask_texture) end

--Gets UI landscape resolution
---@return integer # Resolution
function GameAPI.get_ui_resolution_x() end

--Gets the UI vertical resolution
---@return integer # Resolution
function GameAPI.get_ui_resolution_y() end

--Crop node - Set the image mask of the crop node
---@param role py.Role # Player
---@param comp_uid string # Control uid
---@param stencil_texture integer # Picture id
function GameAPI.set_clipping_node_stencil_texture(role, comp_uid, stencil_texture) end

--Cutting a node - Set the node to be cut. Enable reverse cutting
---@param role py.Role # Player
---@param comp_uid string # Control uid
---@param is_inverted boolean # Whether to reverse cut
function GameAPI.set_clipping_node_inverted(role, comp_uid, is_inverted) end

--Obtain a skill instance based on the unique ID of the skill
---@param ability_global_id integer # ID
---@return py.Ability # skill
function GameAPI.get_ability_by_ability_global_id(ability_global_id) end

--Gets the md5 value of the string
---@param original_str string # Raw string
---@return string # md5 value
function GameAPI.api_get_string_md5(original_str) end

--Generate an RSA key pair
---@return py.List # Public and private keys
function GameAPI.generate_rsa_keys() end

--Encrypt messages using a public key
---@param public_key string # Public key
---@param message string # Original message
---@return string # Encrypted message
function GameAPI.rsa_encrypt_message(public_key, message) end

--Decrypt the message using the private key
---@param private_key string # Private key
---@param encrypted_message string # Encrypted message
---@return string # The decrypted message
function GameAPI.rsa_decrypt_message(private_key, encrypted_message) end

--Resets the overall visibility of blood strips
---@param unit py.Unit # unit
---@param role? py.Role # Player
function GameAPI.reset_billboard_overall_visibility(unit, role) end

--Request the value of the latest leaderboard
---@param archive_key integer # Player save field
---@param lua_func function # Callback function
function GameAPI.lua_request_get_map_rank(archive_key, lua_func) end

--Bind the magic effect remaining cycle to the properties of the player interface control
---@param role py.Role # Player
---@param ui_comp string # Control uid
---@param ui_comp_attr string # Control property field
---@param modifier py.ModifierEntity # Skill entity object
function GameAPI.set_ui_comp_bind_modifier_cycle(role, ui_comp, ui_comp_attr, modifier) end

--Serialized KV
---@param kvbase py.Actor # Actor
---@return string # Serialization result
function GameAPI.api_serialize_kv(kvbase) end

--Deserialization KV
---@param kvbase py.Actor # Actor
---@param json_str string # kv
function GameAPI.api_deserialize_kv(kvbase, json_str) end

--Set the player's priority for clicking units
---@param role py.Role # Player
---@param unit_type integer # Unit type
---@param priority integer # priority
function GameAPI.api_set_player_select_unit_priority(role, unit_type, priority) end

--Modify object material
---@param obj py.Actor # object
---@param material_id integer # Material id
function GameAPI.set_obj_material_param(obj, material_id) end

--Minimap - Set the bottom frame of the hero minimap avatar
---@param role py.Role # Player
---@param unit py.Unit # unit
---@param image_id py.Texture # Picture id
function GameAPI.api_set_hero_mini_map_frame(role, unit, image_id) end

--【 Asynchronous 】 Gets the current percentage position of the local player grid list
---@param comp_name string # Control uid
---@param direction integer # Horizontal/vertical
---@return number # percent
function GameAPI.get_grid_view_percent(comp_name, direction) end

--Set the text stripper
---@param role py.Role # Player
---@param comp_name string # Control uid
---@param enable boolean # Switch
---@param width? integer # Degree of thickness
---@param color? string # hex
---@param alpha? number # A
function GameAPI.set_ui_text_strike_through(role, comp_name, enable, width, color, alpha) end

--Set text underline
---@param role py.Role # Player
---@param comp_name string # Control uid
---@param enable boolean # Switch
function GameAPI.set_ui_text_under_line(role, comp_name, enable) end

--Set text italics
---@param role py.Role # Player
---@param comp_name string # Control uid
---@param enable boolean # Switch
---@param radius? number # Degree of inclination
function GameAPI.set_ui_text_italics(role, comp_name, enable, radius) end
