--This file is generated by tools/genGameAPI, do not modify it manually.
---@meta

---@class py.ModifierEntity
local ModifierEntity = {}

--Increases the maximum number of buff layers
---@param attr_num integer # Integer attribute value
function ModifierEntity:api_add_buff_max_layer(attr_num) end

--Increased the number of buff instance layers
---@param plus_layer integer # Integer attribute value
function ModifierEntity:api_add_buff_layer(plus_layer) end

--Increases the remaining duration of the buff
---@param residue_time py.Fixed # Floating point number remaining time
function ModifierEntity:api_add_buff_residue_time(residue_time) end

--Added the buff floating-point attribute effect
---@param attr_name string # Attribute name
---@param attr_num py.Fixed # Floating-point attribute value
function ModifierEntity:api_add_float_shield(attr_name, attr_num) end

--Increase the cycle time of cycle events
---@param add_cycle_time py.Fixed # Floating-point attribute value
function ModifierEntity:api_add_cycle_time(add_cycle_time) end

--Block incoming magic effects
---@return boolean? # Returned value
function ModifierEntity:api_prevent_will_modifier() end

--Remove magic effects
---@return boolean? # Returned value
function ModifierEntity:api_remove() end

--Increases the range of magic aura effects
---@param add_value py.Fixed # Floating-point attribute value
function ModifierEntity:api_add_modifier_halo_influence_rng(add_value) end

--Gain effect carrier
---@return py.Unit? # Effect carrier
function ModifierEntity:api_get_owner() end

--Get effect release
---@return py.Unit? # Effect release
function ModifierEntity:api_get_releaser() end

--Gets the remaining duration
---@return py.Fixed? # Residual duration
function ModifierEntity:api_get_residue_time() end

--Gets the elapsed time
---@return py.Fixed? # Already duration
function ModifierEntity:api_get_passed_time() end

--Gets the id of the buff associated skill
---@return integer? # Maximum number of stacks
function ModifierEntity:api_get_from_ability_id() end

--Gets the maximum number of stacks buff
---@return integer? # Maximum number of stacks
function ModifierEntity:api_get_layer_max() end

--Get buff class
---@param attr_name string # Attribute name
---@return py.ModifierType? # Magic effect categories
function ModifierEntity:api_get_modifier_type(attr_name) end

--Gets the buff influence type
---@param attr_name string # Attribute name
---@return py.ModifierEffectType? # Magic effects affect classes
function ModifierEntity:api_get_modifier_effect_type(attr_name) end

--Gets the buff floating-point property effect
---@param attr_name string # Attribute name
---@return py.Fixed? # Floating-point return type
function ModifierEntity:api_get_float_attr(attr_name) end

--Gets the buff cycle
---@return py.Fixed? # Floating-point return type
function ModifierEntity:api_get_cycle_time() end

--Gets the sub-halo type of halo magic effect
---@return py.ModifierKey? # Magic effect number
function ModifierEntity:api_get_sub_halo_modifier_key() end

--Gets the halo entity of the child halo
---@return py.ModifierEntity? # Magic effect object
function ModifierEntity:api_get_halo_modifier_instance() end

--Get the halo range
---@return number? # Halo range
function ModifierEntity:api_get_halo_inf_rng() end

--Get units that are about to receive magic effects
---@return py.Unit? # unit
function ModifierEntity:api_get_will_modifier_unit() end

--Gets the type of magic effect to be obtained
---@return py.ModifierKey? # Magic effect number
function ModifierEntity:api_get_will_modifier_key() end

--Gets the unique id of the buff
---@return integer? # Unique ID for magic effects
function ModifierEntity:api_get_modifier_unique_id() end

--Gets the type key of the buff
---@return py.ModifierKey? # Magic Effects key
function ModifierEntity:api_get_modifier_key() end

--Gets the buff integer attribute effect
---@param attr_name string # Attribute name
---@return integer? # Integer type Return value
function ModifierEntity:api_get_int_attr(attr_name) end

--Gets the buff character attribute effect
---@param attr_name string # Attribute name
---@return string? # Character type Return value
function ModifierEntity:api_get_str_attr(attr_name) end

--Gets whether the buff icon is visible
---@return boolean? # Boolean value
function ModifierEntity:api_get_icon_is_visible() end

--Gain Magic effect level
---@return integer? # Lv.
function ModifierEntity:api_get_modifier_level() end

--Get the stack number of magic effects
---@return integer? # Stack number
function ModifierEntity:api_get_modifier_layer() end

--Set the buff integer attribute effect
---@param attr_num integer # Integer attribute value
function ModifierEntity:api_set_buff_max_layer(attr_num) end

--Set the number of buff instance layers
---@param attr_num integer # Integer attribute value
function ModifierEntity:api_set_buff_layer(attr_num) end

--Sets the remaining duration of the buff
---@param residue_time py.Fixed # Floating point number remaining time
function ModifierEntity:api_set_buff_residue_time(residue_time) end

--Set the buff floating-point property effect
---@param attr_name string # Attribute name
---@param attr_num py.Fixed # Floating-point attribute value
function ModifierEntity:api_set_float_shield(attr_name, attr_num) end

--Set the cycle event
---@param new_cycle_time py.Fixed # Floating-point attribute value
function ModifierEntity:api_set_cycle_time(new_cycle_time) end

--Sets the duration of magic effects
---@param residue_time py.Fixed # Non-negative real value
function ModifierEntity:api_set_duration(residue_time) end

--Sets the string property of buff
---@param name string # Attribute name
---@param value string # Attribute value
function ModifierEntity:api_set_buff_str_attr(name, value) end

--Play music for the player relationship of the unit to which the magic effect belongs
---@param camp_target py.RoleRelation # Player relationship
---@param sid py.AudioKey # Track number
---@param loop boolean # Cyclic or not
function ModifierEntity:api_play_sound_by_mod_for_role_relation(camp_target, sid, loop) end

--Set the halo influence range for magic effects
---@param value py.Fixed # Floating-point attribute value
function ModifierEntity:api_set_modifier_halo_influence_rng(value) end

--Set the icon of the magic effect
---@param icon integer # icon
function ModifierEntity:api_set_modifier_icon(icon) end

--Magic effects added TAB
---@param tag string # tag
function ModifierEntity:api_add_modifier_tag(tag) end

--Magic effect removes labels
---@param tag string # tag
function ModifierEntity:api_remove_modifier_tag(tag) end
