--This file is generated by tools/genGameAPI, do not modify it manually.
---@meta

---@class py.ProjectileEntity
local ProjectileEntity = {}

--Projectile itself object
---@return py.Unit? # Projectile itself object
function ProjectileEntity:api_get_self() end

--Get the unit ID
---@return py.UnitID? # Unit ID
function ProjectileEntity:api_get_id() end

--Projectile number
---@return py.ProjectileKey? # The key to the projectile
function ProjectileEntity:api_get_key() end

--Projective creature
---@return py.Unit? # Projective creature
function ProjectileEntity:api_get_owner() end

--Destroy the projectile object
---@param unit? py.Unit # Destroy the projectile object
---@param immediately? boolean # Remove present now
function ProjectileEntity:api_delete(unit, immediately) end

--Set the projectile position
---@param point py.Point # Projectile position
---@param interpolation? boolean # Whether smooth or not
function ProjectileEntity:api_set_position(point, interpolation) end

--Set the orientation of the projectile
---@param face_angle number # Projectile orientation
function ProjectileEntity:api_set_face_angle(face_angle) end

--Set the projectile rotation
---@param x number # X-axis rotation
---@param z number # Y-axis rotation
---@param y number # Z-axis rotation
function ProjectileEntity:api_set_rotation(x, z, y) end

--Set the scale of the projectile
---@param x number # X-axis scaling
---@param z number # Y-axis scaling
---@param y number # Z-axis scaling
---@param duration? number # Transition time
function ProjectileEntity:api_set_scale(x, z, y, duration) end

--Set the projectile effects playback speed
---@param rate number # Playback speed
function ProjectileEntity:api_set_animation_speed(rate) end

--Set the projectile duration
---@param duration number # duration
function ProjectileEntity:api_set_duration(duration) end

--Increased projectile duration
---@param extra_time number # Duration change value
function ProjectileEntity:api_add_duration(extra_time) end

--Gets the remaining duration of the projectile
---@return number? # The remaining duration of the projectile
function ProjectileEntity:api_get_left_time() end

--Gets projectile height
---@return number? # Projectile height
function ProjectileEntity:api_get_height() end

--Get the projectile Angle
---@return number? # The Angle of the projectile
function ProjectileEntity:api_get_face_angle() end

--Get the projectile position
---@return py.FVector3? # Projectile position
function ProjectileEntity:api_get_position() end

--Gets projectile orientation
---@return py.FVector3? # Projectile orientation
function ProjectileEntity:api_get_face_dir() end

--Projectile elevation
---@param y py.Fixed # Fixed point number
function ProjectileEntity:api_raise_height(y) end

--Gets the string property of the projectile
---@param attr_name string # Attribute name
---@return string? # String type Return value
function ProjectileEntity:api_get_str_attr(attr_name) end

--Sets the string property of the projectile
---@param attr_name string # Attribute name
---@param value string # Attribute value
function ProjectileEntity:api_set_str_attr(attr_name, value) end

--Projectiles add key-value pairs
---@param tag string # TAG
function ProjectileEntity:api_add_tag(tag) end

--Projectiles remove key-value pairs
---@param tag string # TAG
function ProjectileEntity:api_remove_tag(tag) end

--Play music for the player relationship of the unit that the projectile belongs to
---@param camp_target py.RoleRelation # Player relationship
---@param sid py.AudioKey # Track number
---@param loop boolean # Cyclic or not
function ProjectileEntity:api_play_sound_by_proj_for_role_relation(camp_target, sid, loop) end

--A player who retrieves projectiles
---@return py.Role? # Player
function ProjectileEntity:get_projectile_role() end

--Sets the visibility of projectiles to the player
---@param role py.Role # Players/groups of players
---@param is_visible boolean # Visible or not
function ProjectileEntity:api_set_projectile_visible(role, is_visible) end
